package com.sigma.ps.om.structure.errors;

public interface ErrorCodes {
	String MANDATORY_CHAR_NOT_POPULATED = "MANDATORY_CHAR_NOT_POPULATED";
	String BACKEND_SYSTEM_INTERNAL_SERVER_ERROR = "BACKEND_SYSTEM_INTERNAL_SERVER_ERROR";
	String NOT_FOUND = "NOT_FOUND";
	String NULL_RESPONSE = "NULL_RESPONSE";
}